### ISSUE TITLE
Document the current data format

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/mgs_tes_data#1]
Right now, the TES data is stored at ASU in a Vanilla database.  It is also accessible via FTP.  In order to identify an appropriate data storage mechanism, we need to have a firm grasp on what is in the data set.

FTP access: http://static.mars.asu.edu/tes

The FMT files describe what is stored in the TAB files.

DoD: An update to the wiki page with a clear definition of what the current data format is.

**Comment by Kelvinrr** [comment]
Wiki updated with overall table descriptions including basic record info. I imagine I should wait for some kind of review before I close this? Just to be sure what is there is what you had in mind.

**Comment by jlaura** [comment]
:+1: Looks great here.
